/**
 * Hand-maintained schema types for the Phase 1 tables.
 *
 * `src/integrations/supabase/types.ts` is generated by Lovable and is
 * currently empty (the schema did not exist when it last ran). Rather than
 * edit a generated file, the app types against this one. Once the
 * migrations are applied and Lovable regenerates, the two can be merged —
 * the shapes are deliberately identical in style.
 */

export type UserStatus = "invited" | "active" | "suspended" | "locked";
export type RecordStatus = "active" | "inactive";
export type WarehouseType =
  "main" | "shop_floor" | "branch" | "virtual_employee" | "damaged" | "returns" | "in_transit";
export type LocationType = "storage" | "picking" | "receiving" | "dispatch" | "quarantine";
export type NotificationSeverity = "info" | "success" | "warning" | "danger";

type Timestamps = {
  created_at: string;
  updated_at: string;
  created_by: string | null;
  updated_by: string | null;
};

export type BranchRow = Timestamps & {
  id: string;
  code: string;
  name: string;
  is_head_office: boolean;
  address_line1: string | null;
  address_line2: string | null;
  city: string | null;
  country: string;
  phone: string | null;
  email: string | null;
  tax_number: string | null;
  currency_code: string;
  status: RecordStatus;
  notes: string | null;
};

export type WarehouseRow = Timestamps & {
  id: string;
  code: string;
  name: string;
  branch_id: string;
  type: WarehouseType;
  manager_id: string | null;
  address: string | null;
  status: RecordStatus;
  is_default: boolean;
  allow_negative_stock: boolean;
  notes: string | null;
};

export type WarehouseLocationRow = Timestamps & {
  id: string;
  warehouse_id: string;
  code: string;
  name: string;
  type: LocationType;
  status: RecordStatus;
};

export type ProfileRow = Timestamps & {
  id: string;
  employee_code: string | null;
  full_name: string;
  email: string;
  phone: string | null;
  job_title: string | null;
  avatar_url: string | null;
  status: UserStatus;
  default_branch_id: string | null;
  default_warehouse_id: string | null;
  last_login_at: string | null;
  failed_login_count: number;
  locked_until: string | null;
  must_change_password: boolean;
  notes: string | null;
};

export type RoleRow = Timestamps & {
  id: string;
  code: string;
  name: string;
  description: string | null;
  is_system: boolean;
  rank: number;
};

export type PermissionRow = {
  id: string;
  code: string;
  module: string;
  name: string;
  description: string | null;
  created_at: string;
};

export type RolePermissionRow = {
  role_id: string;
  permission_id: string;
  created_at: string;
  created_by: string | null;
};

export type UserRoleRow = {
  id: string;
  user_id: string;
  role_id: string;
  branch_id: string | null;
  created_at: string;
  created_by: string | null;
};

export type SystemSettingsRow = Timestamps & {
  id: boolean;
  company_name: string;
  trading_name: string | null;
  logo_url: string | null;
  tax_number: string | null;
  registration_number: string | null;
  address_line1: string | null;
  address_line2: string | null;
  city: string | null;
  country: string;
  phone: string | null;
  email: string | null;
  website: string | null;
  base_currency: string;
  fiscal_year_start_month: number;
  date_format: string;
  default_tax_rate: number;
  invoice_prefix: string;
  quotation_prefix: string;
  receipt_prefix: string;
  po_prefix: string;
  grn_prefix: string;
  adjustment_prefix: string;
  requisition_prefix: string;
  journal_prefix: string;
};

export type AuditLogRow = {
  id: string;
  user_id: string | null;
  user_email: string | null;
  action: string;
  module: string;
  table_name: string | null;
  record_id: string | null;
  old_value: Record<string, unknown> | null;
  new_value: Record<string, unknown> | null;
  reason: string | null;
  ip_address: string | null;
  user_agent: string | null;
  session_id: string | null;
  created_at: string;
};

export type NotificationRow = {
  id: string;
  user_id: string | null;
  permission_code: string | null;
  type: string;
  title: string;
  body: string | null;
  link: string | null;
  severity: NotificationSeverity;
  read_at: string | null;
  created_at: string;
};

// ---------------------------------------------------------------------
// Phase 2 — catalogue and inventory
// ---------------------------------------------------------------------

export type ProductStatus = "active" | "inactive" | "discontinued";

export type UnitOfMeasureRow = Timestamps & {
  id: string;
  code: string;
  name: string;
  allow_decimal: boolean;
  status: RecordStatus;
};

export type ProductCategoryRow = Timestamps & {
  id: string;
  code: string;
  name: string;
  parent_id: string | null;
  description: string | null;
  status: RecordStatus;
};

export type BrandRow = Timestamps & {
  id: string;
  code: string;
  name: string;
  status: RecordStatus;
};

export type ProductRow = Timestamps & {
  id: string;
  sku: string;
  stock_code: string | null;
  name: string;
  description: string | null;
  category_id: string | null;
  brand_id: string | null;
  uom_id: string;
  default_supplier_id: string | null;
  standard_cost: number;
  selling_price: number;
  tax_rate: number;
  min_stock_level: number;
  max_stock_level: number | null;
  reorder_level: number;
  image_url: string | null;
  notes: string | null;
  track_stock: boolean;
  track_expiry: boolean;
  status: ProductStatus;
};

/** The cost-masked read path: standard_cost is null without the permission. */
export type ProductCatalogueRow = Omit<
  ProductRow,
  "standard_cost" | "created_by" | "updated_by" | "notes" | "default_supplier_id"
> & {
  standard_cost: number | null;
};

export type ProductBarcodeRow = {
  id: string;
  product_id: string;
  barcode: string;
  is_primary: boolean;
  label: string | null;
  created_at: string;
  created_by: string | null;
};

export type InventoryMovementType =
  | "opening_balance"
  | "goods_receipt"
  | "customer_return"
  | "adjustment_increase"
  | "transfer_in"
  | "count_increase"
  | "requisition_return"
  | "sale"
  | "supplier_return"
  | "adjustment_decrease"
  | "transfer_out"
  | "count_decrease"
  | "requisition_issue";

export type InventoryBalanceRow = {
  product_id: string;
  warehouse_id: string;
  quantity: number;
  average_cost: number;
  total_value: number;
  last_movement_at: string | null;
  updated_at: string;
};

export type InventoryMovementRow = {
  id: string;
  movement_no: number;
  product_id: string;
  warehouse_id: string;
  movement_type: InventoryMovementType;
  quantity: number;
  direction: 1 | -1;
  unit_cost: number;
  total_cost: number;
  balance_quantity: number;
  balance_average_cost: number;
  balance_value: number;
  source_module: string | null;
  source_document_type: string | null;
  source_document_id: string | null;
  source_document_number: string | null;
  movement_date: string;
  reason: string | null;
  notes: string | null;
  created_at: string;
  created_by: string | null;
};

// ---------------------------------------------------------------------
// Phase 3 — suppliers
// ---------------------------------------------------------------------

export type SupplierStatus = "active" | "inactive" | "blocked";

export type SupplierRow = Timestamps & {
  id: string;
  code: string;
  name: string;
  trading_name: string | null;
  contact_person: string | null;
  phone: string | null;
  email: string | null;
  website: string | null;
  address_line1: string | null;
  address_line2: string | null;
  city: string | null;
  country: string;
  tax_number: string | null;
  registration_number: string | null;
  currency_code: string;
  payment_terms_days: number;
  credit_limit: number | null;
  opening_balance: number;
  bank_name: string | null;
  bank_account_name: string | null;
  bank_account_number: string | null;
  bank_branch: string | null;
  swift_code: string | null;
  status: SupplierStatus;
  notes: string | null;
};

/** Bank fields are null without a supplier-payment permission. */
export type SupplierDirectoryRow = Omit<SupplierRow, "created_by" | "updated_by">;

// ---------------------------------------------------------------------
// Phase 3 — purchasing
// ---------------------------------------------------------------------

export type RequisitionStatus =
  "draft" | "submitted" | "approved" | "rejected" | "converted" | "cancelled";

export type PurchaseOrderStatus =
  | "draft"
  | "pending_approval"
  | "approved"
  | "partially_received"
  | "received"
  | "cancelled"
  | "closed";

export type GrnStatus = "draft" | "inspected" | "approved" | "posted" | "cancelled";

export type PurchaseRequisitionRow = Timestamps & {
  id: string;
  requisition_no: string;
  branch_id: string | null;
  warehouse_id: string | null;
  requested_by: string | null;
  department: string | null;
  required_date: string | null;
  reason: string | null;
  notes: string | null;
  status: RequisitionStatus;
  submitted_at: string | null;
  approved_by: string | null;
  approved_at: string | null;
  rejected_reason: string | null;
};

export type PurchaseRequisitionLineRow = {
  id: string;
  requisition_id: string;
  line_no: number;
  product_id: string;
  quantity: number;
  estimated_unit_price: number;
  notes: string | null;
  created_at: string;
};

export type PurchaseOrderRow = Timestamps & {
  id: string;
  po_no: string;
  supplier_id: string;
  requisition_id: string | null;
  branch_id: string | null;
  warehouse_id: string;
  order_date: string;
  expected_date: string | null;
  quotation_ref: string | null;
  payment_terms_days: number;
  currency_code: string;
  subtotal: number;
  discount_total: number;
  tax_total: number;
  total: number;
  status: PurchaseOrderStatus;
  approved_by: string | null;
  approved_at: string | null;
  cancelled_reason: string | null;
  notes: string | null;
};

export type PurchaseOrderLineRow = {
  id: string;
  purchase_order_id: string;
  line_no: number;
  product_id: string;
  description: string | null;
  quantity_ordered: number;
  quantity_received: number;
  unit_price: number;
  discount_percent: number;
  tax_rate: number;
  line_total: number;
  created_at: string;
};

export type GoodsReceivedNoteRow = Timestamps & {
  id: string;
  grn_no: string;
  purchase_order_id: string | null;
  supplier_id: string;
  warehouse_id: string;
  branch_id: string | null;
  delivery_note_ref: string | null;
  received_date: string;
  received_by: string | null;
  inspected_by: string | null;
  inspection_notes: string | null;
  approved_by: string | null;
  approved_at: string | null;
  status: GrnStatus;
  posted_at: string | null;
  posted_by: string | null;
  journal_entry_id: string | null;
  total_cost: number;
  notes: string | null;
};

export type GoodsReceivedNoteLineRow = {
  id: string;
  grn_id: string;
  line_no: number;
  purchase_order_line_id: string | null;
  product_id: string;
  quantity_ordered: number;
  quantity_delivered: number;
  quantity_accepted: number;
  quantity_rejected: number;
  unit_cost: number;
  rejection_reason: string | null;
  notes: string | null;
  created_at: string;
};

export type DocumentSequenceRow = {
  doc_type: string;
  prefix: string;
  next_number: number;
  padding: number;
  updated_at: string;
};

// ---------------------------------------------------------------------
// Accounting
// ---------------------------------------------------------------------

export type AccountType = "asset" | "liability" | "equity" | "income" | "cost_of_sales" | "expense";

export type ChartOfAccountRow = Timestamps & {
  id: string;
  account_code: string;
  name: string;
  account_type: AccountType;
  parent_id: string | null;
  description: string | null;
  is_postable: boolean;
  is_system: boolean;
  status: RecordStatus;
};

export type AccountingPeriodRow = Timestamps & {
  id: string;
  fiscal_year: number;
  period_no: number;
  name: string;
  start_date: string;
  end_date: string;
  status: "open" | "locked" | "closed";
  closed_at: string | null;
  closed_by: string | null;
};

export type JournalEntryRow = {
  id: string;
  journal_no: number;
  reference: string;
  journal_date: string;
  posting_date: string;
  period_id: string | null;
  description: string;
  source_module: string | null;
  source_document_type: string | null;
  source_document_id: string | null;
  source_document_number: string | null;
  is_system: boolean;
  total_debit: number;
  total_credit: number;
  status: "posted" | "reversed";
  reverses_journal_id: string | null;
  reversed_by_journal_id: string | null;
  branch_id: string | null;
  created_at: string;
  created_by: string | null;
};

export type JournalEntryLineRow = {
  id: string;
  journal_id: string;
  line_no: number;
  account_id: string;
  description: string | null;
  debit: number;
  credit: number;
  branch_id: string | null;
  supplier_id: string | null;
  customer_id: string | null;
  product_id: string | null;
  created_at: string;
};

// ---------------------------------------------------------------------
// Sales
// ---------------------------------------------------------------------

export type CustomerStatus = "active" | "inactive" | "on_hold";
export type CustomerType = "retail" | "trade" | "contractor" | "government" | "internal";

export type InvoiceStatus =
  | "draft"
  | "awaiting_approval"
  | "approved"
  | "posted"
  | "partially_paid"
  | "paid"
  | "overdue"
  | "cancelled";

export type QuotationStatus =
  "draft" | "sent" | "accepted" | "declined" | "expired" | "converted" | "cancelled";

export type SalesReturnStatus = "draft" | "approved" | "posted" | "cancelled";

export type CustomerRow = Timestamps & {
  id: string;
  code: string;
  name: string;
  trading_name: string | null;
  customer_type: CustomerType;
  contact_person: string | null;
  phone: string | null;
  email: string | null;
  address_line1: string | null;
  address_line2: string | null;
  city: string | null;
  country: string;
  tax_number: string | null;
  registration_number: string | null;
  currency_code: string;
  payment_terms_days: number;
  credit_limit: number | null;
  opening_balance: number;
  salesperson_id: string | null;
  branch_id: string | null;
  status: CustomerStatus;
  notes: string | null;
};

export type SalesQuotationRow = Timestamps & {
  id: string;
  quotation_no: string;
  customer_id: string | null;
  customer_name: string | null;
  branch_id: string | null;
  warehouse_id: string | null;
  salesperson_id: string | null;
  quotation_date: string;
  valid_until: string | null;
  currency_code: string;
  subtotal: number;
  discount_total: number;
  tax_total: number;
  total: number;
  status: QuotationStatus;
  converted_invoice_id: string | null;
  notes: string | null;
};

export type SalesInvoiceRow = Timestamps & {
  id: string;
  invoice_no: string;
  customer_id: string | null;
  customer_name: string | null;
  quotation_id: string | null;
  branch_id: string | null;
  warehouse_id: string;
  salesperson_id: string | null;
  invoice_date: string;
  due_date: string | null;
  currency_code: string;
  payment_type: "cash" | "credit";
  subtotal: number;
  discount_total: number;
  tax_total: number;
  total: number;
  amount_paid: number;
  cost_of_sales: number;
  status: InvoiceStatus;
  posted_at: string | null;
  posted_by: string | null;
  journal_entry_id: string | null;
  cancelled_reason: string | null;
  notes: string | null;
  pos_session_id: string | null;
};

export type SalesDocumentLineRow = {
  id: string;
  line_no: number;
  product_id: string;
  description: string | null;
  quantity: number;
  unit_price: number;
  discount_percent: number;
  tax_rate: number;
  line_total: number;
  created_at: string;
};

export type SalesInvoiceLineRow = SalesDocumentLineRow & {
  invoice_id: string;
  unit_cost: number;
  line_cost: number;
};

export type SalesQuotationLineRow = SalesDocumentLineRow & { quotation_id: string };

export type SalesReturnRow = Timestamps & {
  id: string;
  return_no: string;
  invoice_id: string | null;
  customer_id: string | null;
  customer_name: string | null;
  branch_id: string | null;
  warehouse_id: string;
  return_date: string;
  reason: string;
  restock: boolean;
  subtotal: number;
  tax_total: number;
  total: number;
  cost_of_sales: number;
  status: SalesReturnStatus;
  posted_at: string | null;
  posted_by: string | null;
  journal_entry_id: string | null;
  notes: string | null;
};

export type SalesReturnLineRow = {
  id: string;
  return_id: string;
  line_no: number;
  invoice_line_id: string | null;
  product_id: string;
  quantity: number;
  unit_price: number;
  tax_rate: number;
  line_total: number;
  unit_cost: number;
  line_cost: number;
  created_at: string;
};

export type CustomerReceiptRow = Timestamps & {
  id: string;
  receipt_no: string;
  customer_id: string;
  branch_id: string | null;
  receipt_date: string;
  payment_method: "cash" | "bank_transfer" | "eft" | "cheque" | "card" | "mobile_money";
  reference: string | null;
  amount: number;
  unallocated: number;
  received_by: string | null;
  status: "draft" | "posted" | "cancelled";
  posted_at: string | null;
  journal_entry_id: string | null;
  notes: string | null;
};

export type PosSessionRow = Timestamps & {
  id: string;
  session_no: string;
  branch_id: string | null;
  warehouse_id: string;
  opened_by: string | null;
  opened_at: string;
  opening_float: number;
  closed_by: string | null;
  closed_at: string | null;
  counted_cash: number | null;
  expected_cash: number | null;
  variance: number | null;
  status: "open" | "closed";
  notes: string | null;
};

// ---------------------------------------------------------------------
// Banking and expenses
// ---------------------------------------------------------------------

export type BankAccountRow = Timestamps & {
  id: string;
  name: string;
  bank_name: string;
  account_number: string | null;
  branch_name: string | null;
  swift_code: string | null;
  currency_code: string;
  ledger_account_id: string;
  branch_id: string | null;
  opening_balance: number;
  is_default: boolean;
  status: RecordStatus;
  notes: string | null;
};

export type BankTransactionType =
  "deposit" | "withdrawal" | "charge" | "interest" | "transfer" | "other";

export type BankTransactionRow = {
  id: string;
  reference_no: string;
  bank_account_id: string;
  transaction_date: string;
  description: string;
  reference: string | null;
  amount: number;
  transaction_type: BankTransactionType;
  journal_entry_id: string | null;
  source_module: string | null;
  source_document_type: string | null;
  source_document_id: string | null;
  reconciliation_id: string | null;
  reconciled: boolean;
  created_at: string;
  created_by: string | null;
};

export type BankReconciliationRow = Timestamps & {
  id: string;
  reference_no: string;
  bank_account_id: string;
  statement_date: string;
  statement_balance: number;
  book_balance: number;
  difference: number;
  status: "draft" | "finalised";
  finalised_at: string | null;
  finalised_by: string | null;
  notes: string | null;
};

export type ExpenseCategoryRow = Timestamps & {
  id: string;
  code: string;
  name: string;
  account_id: string;
  status: RecordStatus;
};

export type ExpenseStatus =
  "draft" | "submitted" | "approved" | "posted" | "rejected" | "cancelled";

export type ExpenseRow = Timestamps & {
  id: string;
  expense_no: string;
  category_id: string;
  branch_id: string | null;
  supplier_id: string | null;
  expense_date: string;
  description: string;
  reference: string | null;
  amount: number;
  tax_amount: number;
  total: number;
  payment_method: "cash" | "bank" | "petty_cash" | "card" | "mobile_money";
  bank_account_id: string | null;
  status: ExpenseStatus;
  submitted_at: string | null;
  approved_by: string | null;
  approved_at: string | null;
  posted_at: string | null;
  posted_by: string | null;
  journal_entry_id: string | null;
  attachment_url: string | null;
  notes: string | null;
};

// ---------------------------------------------------------------------
// HR and payroll
// ---------------------------------------------------------------------

export type DepartmentRow = Timestamps & {
  id: string;
  code: string;
  name: string;
  description: string | null;
  branch_id: string | null;
  manager_id: string | null;
  status: RecordStatus;
};

export type PositionRow = Timestamps & {
  id: string;
  code: string;
  title: string;
  department_id: string | null;
  grade: string | null;
  description: string | null;
  status: RecordStatus;
};

export type EmploymentType = "permanent" | "contract" | "casual" | "intern" | "part_time";
export type EmployeeStatus =
  "active" | "probation" | "suspended" | "terminated" | "resigned" | "retired";
export type PayFrequency = "monthly" | "fortnightly" | "weekly" | "daily";

export type EmployeeRow = Timestamps & {
  id: string;
  employee_no: string;
  profile_id: string | null;
  first_name: string;
  last_name: string;
  other_names: string | null;
  national_id: string | null;
  date_of_birth: string | null;
  gender: string | null;
  email: string | null;
  phone: string | null;
  address: string | null;
  emergency_contact_name: string | null;
  emergency_contact_phone: string | null;
  position_id: string | null;
  department_id: string | null;
  branch_id: string | null;
  manager_id: string | null;
  employment_type: EmploymentType;
  hire_date: string;
  probation_end: string | null;
  contract_end: string | null;
  basic_salary: number;
  currency_code: string;
  pay_frequency: PayFrequency;
  bank_name: string | null;
  bank_account_number: string | null;
  bank_branch: string | null;
  tax_number: string | null;
  nssa_number: string | null;
  status: EmployeeStatus;
  termination_date: string | null;
  termination_reason: string | null;
  notes: string | null;
};

/** The salary-masking view. Pay columns are null without the permission. */
export type EmployeeSecureRow = Omit<
  EmployeeRow,
  "basic_salary" | "bank_name" | "bank_account_number" | "bank_branch" | "created_by" | "updated_by"
> & {
  basic_salary: number | null;
  bank_name: string | null;
  bank_account_number: string | null;
  bank_branch: string | null;
};

export type LeaveTypeRow = Timestamps & {
  id: string;
  code: string;
  name: string;
  days_per_year: number;
  is_paid: boolean;
  carry_forward: boolean;
  max_carry_days: number;
  requires_document: boolean;
  status: RecordStatus;
};

export type LeaveStatus = "draft" | "submitted" | "approved" | "rejected" | "cancelled" | "taken";

export type LeaveRequestRow = Timestamps & {
  id: string;
  request_no: string;
  employee_id: string;
  leave_type_id: string;
  start_date: string;
  end_date: string;
  days: number;
  reason: string | null;
  document_url: string | null;
  status: LeaveStatus;
  approved_by: string | null;
  approved_at: string | null;
  rejected_reason: string | null;
};

export type AttendanceStatus =
  "present" | "absent" | "late" | "half_day" | "leave" | "holiday" | "sick";

export type AttendanceRow = Timestamps & {
  id: string;
  employee_id: string;
  attendance_date: string;
  status: AttendanceStatus;
  time_in: string | null;
  time_out: string | null;
  hours_worked: number | null;
  overtime_hours: number;
  notes: string | null;
};

export type PayrollComponentRow = Timestamps & {
  id: string;
  code: string;
  name: string;
  component_type: "earning" | "deduction";
  calculation: "fixed" | "percent_of_basic" | "percent_of_gross";
  default_amount: number;
  default_rate: number;
  is_taxable: boolean;
  is_statutory: boolean;
  is_employer_contribution: boolean;
  ceiling_amount: number | null;
  account_id: string | null;
  sort_order: number;
  status: RecordStatus;
};

export type EmployeeComponentRow = Timestamps & {
  id: string;
  employee_id: string;
  component_id: string;
  amount: number | null;
  rate: number | null;
  effective_from: string;
  effective_to: string | null;
};

export type PayrollTaxBandRow = Timestamps & {
  id: string;
  currency_code: string;
  pay_frequency: PayFrequency;
  effective_from: string;
  lower_limit: number;
  upper_limit: number | null;
  rate: number;
  cumulative_tax: number;
  description: string | null;
};

export type PayrollPeriodRow = Timestamps & {
  id: string;
  name: string;
  fiscal_year: number;
  period_no: number;
  start_date: string;
  end_date: string;
  pay_date: string;
  pay_frequency: PayFrequency;
  status: "open" | "closed";
};

export type PayrollRunStatus =
  "draft" | "calculated" | "approved" | "posted" | "paid" | "cancelled";

export type PayrollRunRow = Timestamps & {
  id: string;
  run_no: string;
  period_id: string;
  branch_id: string | null;
  description: string | null;
  status: PayrollRunStatus;
  employee_count: number;
  total_gross: number;
  total_paye: number;
  total_statutory: number;
  total_deductions: number;
  total_net: number;
  total_employer_cost: number;
  calculated_at: string | null;
  approved_by: string | null;
  approved_at: string | null;
  posted_at: string | null;
  posted_by: string | null;
  paid_at: string | null;
  journal_entry_id: string | null;
};

export type PayslipRow = Timestamps & {
  id: string;
  payslip_no: string;
  run_id: string;
  employee_id: string;
  basic_salary: number;
  total_earnings: number;
  taxable_income: number;
  gross_pay: number;
  paye: number;
  statutory_deductions: number;
  other_deductions: number;
  total_deductions: number;
  net_pay: number;
  employer_contributions: number;
  days_worked: number | null;
  days_absent: number;
  currency_code: string;
};

export type PayslipLineRow = {
  id: string;
  payslip_id: string;
  component_id: string | null;
  line_no: number;
  line_type: "earning" | "deduction";
  description: string;
  amount: number;
  is_employer_contribution: boolean;
  created_at: string;
};

/** Columns the client is allowed to send; the rest are stamped by triggers. */
type Writable<T> = Partial<Omit<T, keyof Timestamps | "id">>;

type TableDef<Row, Insert = Writable<Row>, Update = Writable<Row>> = {
  Row: Row;
  Insert: Insert;
  Update: Update;
  Relationships: [];
};

export type Database = {
  public: {
    Tables: {
      branches: TableDef<BranchRow, Writable<BranchRow> & Pick<BranchRow, "code" | "name">>;
      warehouses: TableDef<
        WarehouseRow,
        Writable<WarehouseRow> & Pick<WarehouseRow, "code" | "name" | "branch_id">
      >;
      warehouse_locations: TableDef<
        WarehouseLocationRow,
        Writable<WarehouseLocationRow> &
          Pick<WarehouseLocationRow, "code" | "name" | "warehouse_id">
      >;
      profiles: TableDef<ProfileRow>;
      roles: TableDef<RoleRow, Writable<RoleRow> & Pick<RoleRow, "code" | "name">>;
      permissions: TableDef<PermissionRow, never, never>;
      role_permissions: TableDef<
        RolePermissionRow,
        Pick<RolePermissionRow, "role_id" | "permission_id">,
        never
      >;
      user_roles: TableDef<
        UserRoleRow,
        Pick<UserRoleRow, "user_id" | "role_id"> & Partial<Pick<UserRoleRow, "branch_id">>,
        never
      >;
      system_settings: TableDef<SystemSettingsRow>;
      audit_logs: TableDef<AuditLogRow, never, never>;
      notifications: TableDef<NotificationRow, never, Pick<NotificationRow, "read_at">>;
      units_of_measure: TableDef<
        UnitOfMeasureRow,
        Writable<UnitOfMeasureRow> & Pick<UnitOfMeasureRow, "code" | "name">
      >;
      product_categories: TableDef<
        ProductCategoryRow,
        Writable<ProductCategoryRow> & Pick<ProductCategoryRow, "code" | "name">
      >;
      brands: TableDef<BrandRow, Writable<BrandRow> & Pick<BrandRow, "code" | "name">>;
      products: TableDef<
        ProductRow,
        Writable<ProductRow> & Pick<ProductRow, "sku" | "name" | "uom_id">
      >;
      product_barcodes: TableDef<
        ProductBarcodeRow,
        Pick<ProductBarcodeRow, "product_id" | "barcode"> &
          Partial<Pick<ProductBarcodeRow, "is_primary" | "label">>,
        Partial<Pick<ProductBarcodeRow, "is_primary" | "label">>
      >;
      inventory_balances: TableDef<InventoryBalanceRow, never, never>;
      inventory_movements: TableDef<InventoryMovementRow, never, never>;
      suppliers: TableDef<SupplierRow, Writable<SupplierRow> & Pick<SupplierRow, "code" | "name">>;
      purchase_requisitions: TableDef<PurchaseRequisitionRow>;
      purchase_requisition_lines: TableDef<PurchaseRequisitionLineRow>;
      purchase_orders: TableDef<PurchaseOrderRow>;
      purchase_order_lines: TableDef<PurchaseOrderLineRow>;
      goods_received_notes: TableDef<GoodsReceivedNoteRow>;
      goods_received_note_lines: TableDef<GoodsReceivedNoteLineRow>;
      // Inserts stay closed — a new sequence is a migration concern. Updates
      // opened in phase6 for the numbering screen, guarded in the database
      // against moving a counter backwards.
      document_sequences: TableDef<
        DocumentSequenceRow,
        never,
        Partial<Pick<DocumentSequenceRow, "prefix" | "padding" | "next_number">>
      >;
      chart_of_accounts: TableDef<ChartOfAccountRow>;
      accounting_periods: TableDef<AccountingPeriodRow>;
      journal_entries: TableDef<JournalEntryRow, never, never>;
      journal_entry_lines: TableDef<JournalEntryLineRow, never, never>;
      customers: TableDef<CustomerRow>;
      sales_quotations: TableDef<SalesQuotationRow>;
      sales_quotation_lines: TableDef<SalesQuotationLineRow>;
      sales_invoices: TableDef<SalesInvoiceRow>;
      sales_invoice_lines: TableDef<SalesInvoiceLineRow>;
      sales_returns: TableDef<SalesReturnRow>;
      sales_return_lines: TableDef<SalesReturnLineRow>;
      customer_receipts: TableDef<CustomerReceiptRow>;
      pos_sessions: TableDef<PosSessionRow, never, never>;
      bank_accounts: TableDef<BankAccountRow>;
      bank_transactions: TableDef<BankTransactionRow>;
      bank_reconciliations: TableDef<BankReconciliationRow>;
      expense_categories: TableDef<ExpenseCategoryRow>;
      expenses: TableDef<ExpenseRow>;
      departments: TableDef<DepartmentRow>;
      positions: TableDef<PositionRow>;
      employees: TableDef<EmployeeRow>;
      employees_secure: TableDef<EmployeeSecureRow, never, never>;
      leave_types: TableDef<LeaveTypeRow>;
      leave_requests: TableDef<LeaveRequestRow>;
      attendance: TableDef<AttendanceRow>;
      payroll_components: TableDef<PayrollComponentRow>;
      employee_components: TableDef<EmployeeComponentRow>;
      payroll_tax_bands: TableDef<PayrollTaxBandRow>;
      payroll_periods: TableDef<PayrollPeriodRow>;
      payroll_runs: TableDef<PayrollRunRow>;
      payslips: TableDef<PayslipRow, never, never>;
      payslip_lines: TableDef<PayslipLineRow, never, never>;
    };
    Views: {
      products_catalogue: { Row: ProductCatalogueRow; Relationships: [] };
      suppliers_directory: { Row: SupplierDirectoryRow; Relationships: [] };
    };
    Functions: {
      has_permission: { Args: { p_code: string }; Returns: boolean };
      has_any_permission: { Args: { p_codes: string[] }; Returns: boolean };
      is_active_user: { Args: Record<string, never>; Returns: boolean };
      my_permissions: { Args: Record<string, never>; Returns: { code: string }[] };
      my_roles: {
        Args: Record<string, never>;
        Returns: { code: string; name: string; rank: number }[];
      };
      record_login_attempt: { Args: { p_email: string; p_succeeded: boolean }; Returns: void };
      find_product_by_scan: {
        Args: { p_code: string };
        Returns: {
          product_id: string;
          sku: string;
          name: string;
          selling_price: number;
          tax_rate: number;
          uom_code: string;
          track_stock: boolean;
          status: string;
        }[];
      };
      inventory_valuation_as_at: {
        Args: { p_as_at?: string; p_warehouse_id?: string | null };
        Returns: {
          product_id: string;
          warehouse_id: string;
          quantity: number;
          average_cost: number;
          total_value: number;
        }[];
      };
      post_goods_received_note: { Args: { p_grn_id: string }; Returns: string };
      post_sales_invoice: { Args: { p_invoice_id: string }; Returns: string };
      open_pos_session: {
        Args: { p_warehouse_id: string; p_branch_id?: string | null; p_opening_float?: number };
        Returns: string;
      };
      close_pos_session: {
        Args: { p_session_id: string; p_counted_cash: number; p_notes?: string | null };
        Returns: number;
      };
      can_post_invoice: { Args: { p_invoice_id: string }; Returns: boolean };
      post_expense: { Args: { p_expense_id: string }; Returns: string };
      calculate_payroll_run: { Args: { p_run_id: string }; Returns: number };
      post_payroll_run: { Args: { p_run_id: string }; Returns: string };
      leave_days_taken: {
        Args: { p_employee_id: string; p_leave_type_id: string; p_year?: number };
        Returns: number;
      };
      calculate_paye: {
        Args: {
          p_taxable: number;
          p_currency?: string;
          p_frequency?: PayFrequency;
          p_as_at?: string;
        };
        Returns: number;
      };
      bank_balance: { Args: { p_bank_account_id: string; p_as_at?: string }; Returns: number };
      post_bank_transaction: {
        Args: {
          p_bank_account_id: string;
          p_date: string;
          p_description: string;
          p_amount: number;
          p_type: BankTransactionType;
          p_contra_account: string;
          p_reference?: string | null;
        };
        Returns: string;
      };
      post_sales_return: { Args: { p_return_id: string }; Returns: string };
      customer_balance: { Args: { p_customer_id: string }; Returns: number };
      next_document_number: { Args: { p_doc_type: string }; Returns: string };
      post_journal_entry: {
        Args: {
          p_reference: string;
          p_description: string;
          p_lines: unknown;
          p_journal_date?: string;
          p_source_module?: string | null;
          p_source_document_type?: string | null;
          p_source_document_id?: string | null;
          p_source_document_number?: string | null;
          p_branch_id?: string | null;
          p_is_system?: boolean;
          p_reverses_journal_id?: string | null;
        };
        Returns: string;
      };
      reverse_journal_entry: {
        Args: { p_journal_id: string; p_reason: string; p_reversal_date?: string };
        Returns: string;
      };
      trial_balance: {
        Args: { p_as_at?: string; p_branch_id?: string | null };
        Returns: {
          account_code: string;
          account_name: string;
          account_type: AccountType;
          total_debit: number;
          total_credit: number;
          balance: number;
        }[];
      };
      post_inventory_movement: {
        Args: {
          p_product_id: string;
          p_warehouse_id: string;
          p_movement_type: InventoryMovementType;
          p_quantity: number;
          p_unit_cost?: number | null;
          p_source_module?: string | null;
          p_source_document_type?: string | null;
          p_source_document_id?: string | null;
          p_source_document_number?: string | null;
          p_movement_date?: string | null;
          p_reason?: string | null;
          p_notes?: string | null;
        };
        Returns: string;
      };
    };
    Enums: Record<never, never>;
    CompositeTypes: Record<never, never>;
  };
};
