/**
 * Hand-maintained schema types for the Phase 1 tables.
 *
 * `src/integrations/supabase/types.ts` is generated by Lovable and is
 * currently empty (the schema did not exist when it last ran). Rather than
 * edit a generated file, the app types against this one. Once the
 * migrations are applied and Lovable regenerates, the two can be merged —
 * the shapes are deliberately identical in style.
 */

export type UserStatus = "invited" | "active" | "suspended" | "locked";
export type RecordStatus = "active" | "inactive";
export type WarehouseType =
  "main" | "shop_floor" | "branch" | "virtual_employee" | "damaged" | "returns" | "in_transit";
export type LocationType = "storage" | "picking" | "receiving" | "dispatch" | "quarantine";
export type NotificationSeverity = "info" | "success" | "warning" | "danger";

type Timestamps = {
  created_at: string;
  updated_at: string;
  created_by: string | null;
  updated_by: string | null;
};

export type BranchRow = Timestamps & {
  id: string;
  code: string;
  name: string;
  is_head_office: boolean;
  address_line1: string | null;
  address_line2: string | null;
  city: string | null;
  country: string;
  phone: string | null;
  email: string | null;
  tax_number: string | null;
  currency_code: string;
  status: RecordStatus;
  notes: string | null;
};

export type WarehouseRow = Timestamps & {
  id: string;
  code: string;
  name: string;
  branch_id: string;
  type: WarehouseType;
  manager_id: string | null;
  address: string | null;
  status: RecordStatus;
  is_default: boolean;
  allow_negative_stock: boolean;
  notes: string | null;
};

export type WarehouseLocationRow = Timestamps & {
  id: string;
  warehouse_id: string;
  code: string;
  name: string;
  type: LocationType;
  status: RecordStatus;
};

export type ProfileRow = Timestamps & {
  id: string;
  employee_code: string | null;
  full_name: string;
  email: string;
  phone: string | null;
  job_title: string | null;
  avatar_url: string | null;
  status: UserStatus;
  default_branch_id: string | null;
  default_warehouse_id: string | null;
  last_login_at: string | null;
  failed_login_count: number;
  locked_until: string | null;
  must_change_password: boolean;
  notes: string | null;
};

export type RoleRow = Timestamps & {
  id: string;
  code: string;
  name: string;
  description: string | null;
  is_system: boolean;
  rank: number;
};

export type PermissionRow = {
  id: string;
  code: string;
  module: string;
  name: string;
  description: string | null;
  created_at: string;
};

export type RolePermissionRow = {
  role_id: string;
  permission_id: string;
  created_at: string;
  created_by: string | null;
};

export type UserRoleRow = {
  id: string;
  user_id: string;
  role_id: string;
  branch_id: string | null;
  created_at: string;
  created_by: string | null;
};

export type SystemSettingsRow = Timestamps & {
  id: boolean;
  company_name: string;
  trading_name: string | null;
  logo_url: string | null;
  tax_number: string | null;
  registration_number: string | null;
  address_line1: string | null;
  address_line2: string | null;
  city: string | null;
  country: string;
  phone: string | null;
  email: string | null;
  website: string | null;
  base_currency: string;
  fiscal_year_start_month: number;
  date_format: string;
  default_tax_rate: number;
  invoice_prefix: string;
  quotation_prefix: string;
  receipt_prefix: string;
  po_prefix: string;
  grn_prefix: string;
  adjustment_prefix: string;
  requisition_prefix: string;
  journal_prefix: string;
};

export type AuditLogRow = {
  id: string;
  user_id: string | null;
  user_email: string | null;
  action: string;
  module: string;
  table_name: string | null;
  record_id: string | null;
  old_value: Record<string, unknown> | null;
  new_value: Record<string, unknown> | null;
  reason: string | null;
  ip_address: string | null;
  user_agent: string | null;
  session_id: string | null;
  created_at: string;
};

export type NotificationRow = {
  id: string;
  user_id: string | null;
  permission_code: string | null;
  type: string;
  title: string;
  body: string | null;
  link: string | null;
  severity: NotificationSeverity;
  read_at: string | null;
  created_at: string;
};

/** Columns the client is allowed to send; the rest are stamped by triggers. */
type Writable<T> = Partial<Omit<T, keyof Timestamps | "id">>;

type TableDef<Row, Insert = Writable<Row>, Update = Writable<Row>> = {
  Row: Row;
  Insert: Insert;
  Update: Update;
  Relationships: [];
};

export type Database = {
  public: {
    Tables: {
      branches: TableDef<BranchRow, Writable<BranchRow> & Pick<BranchRow, "code" | "name">>;
      warehouses: TableDef<
        WarehouseRow,
        Writable<WarehouseRow> & Pick<WarehouseRow, "code" | "name" | "branch_id">
      >;
      warehouse_locations: TableDef<
        WarehouseLocationRow,
        Writable<WarehouseLocationRow> &
          Pick<WarehouseLocationRow, "code" | "name" | "warehouse_id">
      >;
      profiles: TableDef<ProfileRow>;
      roles: TableDef<RoleRow, Writable<RoleRow> & Pick<RoleRow, "code" | "name">>;
      permissions: TableDef<PermissionRow, never, never>;
      role_permissions: TableDef<
        RolePermissionRow,
        Pick<RolePermissionRow, "role_id" | "permission_id">,
        never
      >;
      user_roles: TableDef<
        UserRoleRow,
        Pick<UserRoleRow, "user_id" | "role_id"> & Partial<Pick<UserRoleRow, "branch_id">>,
        never
      >;
      system_settings: TableDef<SystemSettingsRow>;
      audit_logs: TableDef<AuditLogRow, never, never>;
      notifications: TableDef<NotificationRow, never, Pick<NotificationRow, "read_at">>;
    };
    Views: Record<never, never>;
    Functions: {
      has_permission: { Args: { p_code: string }; Returns: boolean };
      has_any_permission: { Args: { p_codes: string[] }; Returns: boolean };
      is_active_user: { Args: Record<string, never>; Returns: boolean };
      my_permissions: { Args: Record<string, never>; Returns: { code: string }[] };
      my_roles: {
        Args: Record<string, never>;
        Returns: { code: string; name: string; rank: number }[];
      };
      record_login_attempt: { Args: { p_email: string; p_succeeded: boolean }; Returns: void };
    };
    Enums: Record<never, never>;
    CompositeTypes: Record<never, never>;
  };
};
