import type { SupabaseClient } from "@supabase/supabase-js";

import { supabase as generatedClient } from "@/integrations/supabase/client";
import type { Database } from "./database.types";

/**
 * The single Supabase client for the app, typed against our schema.
 *
 * `src/integrations/supabase/client.ts` is generated by Lovable and must not
 * be edited by hand — but its `Database` generic is still empty. Re-typing it
 * here gives the whole app schema-aware queries without touching that file.
 */
export const db = generatedClient as unknown as SupabaseClient<Database>;

/** Auth lives on the same client; aliased for readable call sites. */
export const auth = db.auth;

export class SupabaseError extends Error {
  constructor(
    message: string,
    readonly code?: string,
    readonly details?: string,
  ) {
    super(message);
    this.name = "SupabaseError";
  }
}

/**
 * Unwraps a PostgREST result, turning the error branch into a throw so
 * TanStack Query can drive the error state.
 */
export function unwrap<T>(result: { data: T | null; error: { message: string; code?: string; details?: string } | null }): T {
  if (result.error) {
    throw new SupabaseError(
      humaniseError(result.error.message, result.error.code),
      result.error.code,
      result.error.details,
    );
  }
  if (result.data === null) {
    throw new SupabaseError("The record could not be found.");
  }
  return result.data;
}

/** Same as `unwrap`, but a missing row is a legitimate `null`. */
export function unwrapMaybe<T>(result: {
  data: T | null;
  error: { message: string; code?: string; details?: string } | null;
}): T | null {
  if (result.error) {
    throw new SupabaseError(
      humaniseError(result.error.message, result.error.code),
      result.error.code,
      result.error.details,
    );
  }
  return result.data;
}

/** Postgres error codes surface to users constantly; make them readable. */
export function humaniseError(message: string, code?: string): string {
  switch (code) {
    case "23505":
      return "That code is already in use. Choose a different one.";
    case "23503":
      return "This record is still referenced elsewhere and cannot be changed.";
    case "23514":
      return "Some of those values are not allowed. Check the highlighted fields.";
    case "42501":
    case "PGRST301":
      return "You do not have permission to do that.";
    case "PGRST116":
      return "That record no longer exists.";
    default:
      // RLS denials arrive as a generic message; make the cause obvious.
      if (message.includes("row-level security")) {
        return "You do not have permission to do that.";
      }
      return message;
  }
}
