/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GoodsReceivingRouteImport } from './routes/goods-receiving'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as PosRouteImport } from './routes/pos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GoodsReceivingRoute = GoodsReceivingRouteImport.update({
  id: '/goods-receiving',
  path: '/goods-receiving',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const PosRoute = PosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/goods-receiving': typeof GoodsReceivingRoute
  '/inventory': typeof InventoryRoute
  '/pos': typeof PosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/goods-receiving': typeof GoodsReceivingRoute
  '/inventory': typeof InventoryRoute
  '/pos': typeof PosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/goods-receiving': typeof GoodsReceivingRoute
  '/inventory': typeof InventoryRoute
  '/pos': typeof PosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/goods-receiving' | '/inventory' | '/pos'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/goods-receiving' | '/inventory' | '/pos'
  id: '__root__' | '/' | '/goods-receiving' | '/inventory' | '/pos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GoodsReceivingRoute: typeof GoodsReceivingRoute
  InventoryRoute: typeof InventoryRoute
  PosRoute: typeof PosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goods-receiving': {
      id: '/goods-receiving'
      path: '/goods-receiving'
      fullPath: '/goods-receiving'
      preLoaderRoute: typeof GoodsReceivingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos': {
      id: '/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GoodsReceivingRoute: GoodsReceivingRoute,
  InventoryRoute: InventoryRoute,
  PosRoute: PosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
