/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAccountingRouteImport } from './routes/_app/accounting'
import { Route as AppAuditTrailRouteImport } from './routes/_app/audit-trail'
import { Route as AppBankingRouteImport } from './routes/_app/banking'
import { Route as AppCustomersRouteImport } from './routes/_app/customers'
import { Route as AppExpensesRouteImport } from './routes/_app/expenses'
import { Route as AppGoodsReceivingRouteImport } from './routes/_app/goods-receiving'
import { Route as AppHrRouteImport } from './routes/_app/hr'
import { Route as AppInventoryRouteImport } from './routes/_app/inventory'
import { Route as AppPayrollRouteImport } from './routes/_app/payroll'
import { Route as AppPosRouteImport } from './routes/_app/pos'
import { Route as AppProductsRouteImport } from './routes/_app/products'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppPurchasesRouteImport } from './routes/_app/purchases'
import { Route as AppRequisitionsRouteImport } from './routes/_app/requisitions'
import { Route as AppSalesRouteImport } from './routes/_app/sales'
import { Route as AppSuppliersRouteImport } from './routes/_app/suppliers'
import { Route as AppUsersRouteImport } from './routes/_app/users'
import { Route as AppWarehousesRouteImport } from './routes/_app/warehouses'
import { Route as AppSettingsBranchesRouteImport } from './routes/_app/settings/branches'
import { Route as AppSettingsCompanyRouteImport } from './routes/_app/settings/company'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountingRoute = AppAccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditTrailRoute = AppAuditTrailRouteImport.update({
  id: '/audit-trail',
  path: '/audit-trail',
  getParentRoute: () => AppRoute,
} as any)
const AppBankingRoute = AppBankingRouteImport.update({
  id: '/banking',
  path: '/banking',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesRoute = AppExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppGoodsReceivingRoute = AppGoodsReceivingRouteImport.update({
  id: '/goods-receiving',
  path: '/goods-receiving',
  getParentRoute: () => AppRoute,
} as any)
const AppHrRoute = AppHrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppPayrollRoute = AppPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AppRoute,
} as any)
const AppPosRoute = AppPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchasesRoute = AppPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => AppRoute,
} as any)
const AppRequisitionsRoute = AppRequisitionsRouteImport.update({
  id: '/requisitions',
  path: '/requisitions',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesRoute = AppSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AppRoute,
} as any)
const AppSuppliersRoute = AppSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppWarehousesRoute = AppWarehousesRouteImport.update({
  id: '/warehouses',
  path: '/warehouses',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsBranchesRoute = AppSettingsBranchesRouteImport.update({
  id: '/settings/branches',
  path: '/settings/branches',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsCompanyRoute = AppSettingsCompanyRouteImport.update({
  id: '/settings/company',
  path: '/settings/company',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/accounting': typeof AppAccountingRoute
  '/audit-trail': typeof AppAuditTrailRoute
  '/banking': typeof AppBankingRoute
  '/customers': typeof AppCustomersRoute
  '/expenses': typeof AppExpensesRoute
  '/goods-receiving': typeof AppGoodsReceivingRoute
  '/hr': typeof AppHrRoute
  '/inventory': typeof AppInventoryRoute
  '/payroll': typeof AppPayrollRoute
  '/pos': typeof AppPosRoute
  '/products': typeof AppProductsRoute
  '/profile': typeof AppProfileRoute
  '/purchases': typeof AppPurchasesRoute
  '/requisitions': typeof AppRequisitionsRoute
  '/sales': typeof AppSalesRoute
  '/suppliers': typeof AppSuppliersRoute
  '/users': typeof AppUsersRoute
  '/warehouses': typeof AppWarehousesRoute
  '/settings/branches': typeof AppSettingsBranchesRoute
  '/settings/company': typeof AppSettingsCompanyRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/accounting': typeof AppAccountingRoute
  '/audit-trail': typeof AppAuditTrailRoute
  '/banking': typeof AppBankingRoute
  '/customers': typeof AppCustomersRoute
  '/expenses': typeof AppExpensesRoute
  '/goods-receiving': typeof AppGoodsReceivingRoute
  '/hr': typeof AppHrRoute
  '/inventory': typeof AppInventoryRoute
  '/payroll': typeof AppPayrollRoute
  '/pos': typeof AppPosRoute
  '/products': typeof AppProductsRoute
  '/profile': typeof AppProfileRoute
  '/purchases': typeof AppPurchasesRoute
  '/requisitions': typeof AppRequisitionsRoute
  '/sales': typeof AppSalesRoute
  '/suppliers': typeof AppSuppliersRoute
  '/users': typeof AppUsersRoute
  '/warehouses': typeof AppWarehousesRoute
  '/': typeof AppIndexRoute
  '/settings/branches': typeof AppSettingsBranchesRoute
  '/settings/company': typeof AppSettingsCompanyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/accounting': typeof AppAccountingRoute
  '/_app/audit-trail': typeof AppAuditTrailRoute
  '/_app/banking': typeof AppBankingRoute
  '/_app/customers': typeof AppCustomersRoute
  '/_app/expenses': typeof AppExpensesRoute
  '/_app/goods-receiving': typeof AppGoodsReceivingRoute
  '/_app/hr': typeof AppHrRoute
  '/_app/inventory': typeof AppInventoryRoute
  '/_app/payroll': typeof AppPayrollRoute
  '/_app/pos': typeof AppPosRoute
  '/_app/products': typeof AppProductsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/purchases': typeof AppPurchasesRoute
  '/_app/requisitions': typeof AppRequisitionsRoute
  '/_app/sales': typeof AppSalesRoute
  '/_app/suppliers': typeof AppSuppliersRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/warehouses': typeof AppWarehousesRoute
  '/_app/': typeof AppIndexRoute
  '/_app/settings/branches': typeof AppSettingsBranchesRoute
  '/_app/settings/company': typeof AppSettingsCompanyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/accounting'
    | '/audit-trail'
    | '/banking'
    | '/customers'
    | '/expenses'
    | '/goods-receiving'
    | '/hr'
    | '/inventory'
    | '/payroll'
    | '/pos'
    | '/products'
    | '/profile'
    | '/purchases'
    | '/requisitions'
    | '/sales'
    | '/suppliers'
    | '/users'
    | '/warehouses'
    | '/settings/branches'
    | '/settings/company'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/accounting'
    | '/audit-trail'
    | '/banking'
    | '/customers'
    | '/expenses'
    | '/goods-receiving'
    | '/hr'
    | '/inventory'
    | '/payroll'
    | '/pos'
    | '/products'
    | '/profile'
    | '/purchases'
    | '/requisitions'
    | '/sales'
    | '/suppliers'
    | '/users'
    | '/warehouses'
    | '/'
    | '/settings/branches'
    | '/settings/company'
  id:
    | '__root__'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/_app/accounting'
    | '/_app/audit-trail'
    | '/_app/banking'
    | '/_app/customers'
    | '/_app/expenses'
    | '/_app/goods-receiving'
    | '/_app/hr'
    | '/_app/inventory'
    | '/_app/payroll'
    | '/_app/pos'
    | '/_app/products'
    | '/_app/profile'
    | '/_app/purchases'
    | '/_app/requisitions'
    | '/_app/sales'
    | '/_app/suppliers'
    | '/_app/users'
    | '/_app/warehouses'
    | '/_app/'
    | '/_app/settings/branches'
    | '/_app/settings/company'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounting': {
      id: '/_app/accounting'
      path: '/accounting'
      fullPath: '/accounting'
      preLoaderRoute: typeof AppAccountingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit-trail': {
      id: '/_app/audit-trail'
      path: '/audit-trail'
      fullPath: '/audit-trail'
      preLoaderRoute: typeof AppAuditTrailRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/banking': {
      id: '/_app/banking'
      path: '/banking'
      fullPath: '/banking'
      preLoaderRoute: typeof AppBankingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers': {
      id: '/_app/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expenses': {
      id: '/_app/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AppExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/goods-receiving': {
      id: '/_app/goods-receiving'
      path: '/goods-receiving'
      fullPath: '/goods-receiving'
      preLoaderRoute: typeof AppGoodsReceivingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr': {
      id: '/_app/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof AppHrRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payroll': {
      id: '/_app/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof AppPayrollRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pos': {
      id: '/_app/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof AppPosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products': {
      id: '/_app/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/purchases': {
      id: '/_app/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof AppPurchasesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/requisitions': {
      id: '/_app/requisitions'
      path: '/requisitions'
      fullPath: '/requisitions'
      preLoaderRoute: typeof AppRequisitionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales': {
      id: '/_app/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AppSalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/suppliers': {
      id: '/_app/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AppSuppliersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/warehouses': {
      id: '/_app/warehouses'
      path: '/warehouses'
      fullPath: '/warehouses'
      preLoaderRoute: typeof AppWarehousesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/branches': {
      id: '/_app/settings/branches'
      path: '/settings/branches'
      fullPath: '/settings/branches'
      preLoaderRoute: typeof AppSettingsBranchesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/company': {
      id: '/_app/settings/company'
      path: '/settings/company'
      fullPath: '/settings/company'
      preLoaderRoute: typeof AppSettingsCompanyRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAccountingRoute: typeof AppAccountingRoute
  AppAuditTrailRoute: typeof AppAuditTrailRoute
  AppBankingRoute: typeof AppBankingRoute
  AppCustomersRoute: typeof AppCustomersRoute
  AppExpensesRoute: typeof AppExpensesRoute
  AppGoodsReceivingRoute: typeof AppGoodsReceivingRoute
  AppHrRoute: typeof AppHrRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppPayrollRoute: typeof AppPayrollRoute
  AppPosRoute: typeof AppPosRoute
  AppProductsRoute: typeof AppProductsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppPurchasesRoute: typeof AppPurchasesRoute
  AppRequisitionsRoute: typeof AppRequisitionsRoute
  AppSalesRoute: typeof AppSalesRoute
  AppSuppliersRoute: typeof AppSuppliersRoute
  AppUsersRoute: typeof AppUsersRoute
  AppWarehousesRoute: typeof AppWarehousesRoute
  AppIndexRoute: typeof AppIndexRoute
  AppSettingsBranchesRoute: typeof AppSettingsBranchesRoute
  AppSettingsCompanyRoute: typeof AppSettingsCompanyRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountingRoute: AppAccountingRoute,
  AppAuditTrailRoute: AppAuditTrailRoute,
  AppBankingRoute: AppBankingRoute,
  AppCustomersRoute: AppCustomersRoute,
  AppExpensesRoute: AppExpensesRoute,
  AppGoodsReceivingRoute: AppGoodsReceivingRoute,
  AppHrRoute: AppHrRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppPayrollRoute: AppPayrollRoute,
  AppPosRoute: AppPosRoute,
  AppProductsRoute: AppProductsRoute,
  AppProfileRoute: AppProfileRoute,
  AppPurchasesRoute: AppPurchasesRoute,
  AppRequisitionsRoute: AppRequisitionsRoute,
  AppSalesRoute: AppSalesRoute,
  AppSuppliersRoute: AppSuppliersRoute,
  AppUsersRoute: AppUsersRoute,
  AppWarehousesRoute: AppWarehousesRoute,
  AppIndexRoute: AppIndexRoute,
  AppSettingsBranchesRoute: AppSettingsBranchesRoute,
  AppSettingsCompanyRoute: AppSettingsCompanyRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
