-- =====================================================================
-- Builders Paradise ERP — Phase 2: inventory ledger and balances
--
-- The single place stock ever changes. GRNs, POS sales, adjustments,
-- transfers, requisitions and counts all post through
-- public.post_inventory_movement() — nothing writes inventory_balances
-- directly, and posted movements are immutable.
--
-- Costing: WEIGHTED AVERAGE, maintained per (product, warehouse).
--   inbound  -> new_avg = (qty*avg + in_qty*in_cost) / (qty + in_qty)
--   outbound -> valued at the current average; the average does not move
-- =====================================================================

-- ---------------------------------------------------------------------
-- Balances — one row per product per warehouse
-- ---------------------------------------------------------------------

create table if not exists public.inventory_balances (
  product_id     uuid not null references public.products (id) on delete restrict,
  warehouse_id   uuid not null references public.warehouses (id) on delete restrict,
  quantity       numeric(18, 4) not null default 0,
  -- Weighted average unit cost. Four decimals: cement at $0.0001 matters
  -- when a movement is 40,000 units.
  average_cost   numeric(18, 6) not null default 0,
  -- Held as a column rather than computed so the valuation report is a
  -- sum, not a per-row multiplication that can drift from the ledger.
  total_value    numeric(18, 4) not null default 0,
  last_movement_at timestamptz,
  updated_at     timestamptz not null default now(),
  primary key (product_id, warehouse_id),
  constraint inventory_balances_cost_check check (average_cost >= 0)
);

create index if not exists inventory_balances_warehouse_idx on public.inventory_balances (warehouse_id);
create index if not exists inventory_balances_product_idx on public.inventory_balances (product_id);

-- ---------------------------------------------------------------------
-- Movements — append-only ledger
-- ---------------------------------------------------------------------

create table if not exists public.inventory_movements (
  id                     uuid primary key default gen_random_uuid(),
  movement_no            bigint generated by default as identity,
  product_id             uuid not null references public.products (id) on delete restrict,
  warehouse_id           uuid not null references public.warehouses (id) on delete restrict,
  movement_type          text not null,
  -- Always positive; direction comes from movement_type.
  quantity               numeric(18, 4) not null,
  direction              smallint not null,
  unit_cost              numeric(18, 6) not null,
  total_cost             numeric(18, 4) not null,

  -- Balance snapshot AFTER this movement, so the ledger reconstructs
  -- historical valuation without replaying every row.
  balance_quantity       numeric(18, 4) not null,
  balance_average_cost   numeric(18, 6) not null,
  balance_value          numeric(18, 4) not null,

  -- Where it came from.
  source_module          text,
  source_document_type   text,
  source_document_id     uuid,
  source_document_number text,

  movement_date          date not null default current_date,
  reason                 text,
  notes                  text,

  created_at             timestamptz not null default now(),
  created_by             uuid references public.profiles (id) on delete set null,

  constraint inventory_movements_quantity_check check (quantity > 0),
  constraint inventory_movements_direction_check check (direction in (-1, 1)),
  constraint inventory_movements_cost_check check (unit_cost >= 0),
  constraint inventory_movements_type_check check (
    movement_type in (
      'opening_balance', 'goods_receipt', 'customer_return', 'adjustment_increase',
      'transfer_in', 'count_increase', 'requisition_return',
      'sale', 'supplier_return', 'adjustment_decrease',
      'transfer_out', 'count_decrease', 'requisition_issue'
    )
  )
);

create index if not exists inventory_movements_product_idx on public.inventory_movements (product_id, movement_date desc);
create index if not exists inventory_movements_warehouse_idx on public.inventory_movements (warehouse_id, movement_date desc);
create index if not exists inventory_movements_date_idx on public.inventory_movements (movement_date desc);
create index if not exists inventory_movements_source_idx on public.inventory_movements (source_document_type, source_document_id);
create index if not exists inventory_movements_type_idx on public.inventory_movements (movement_type);
create index if not exists inventory_movements_user_idx on public.inventory_movements (created_by);

-- ---------------------------------------------------------------------
-- Direction of each movement type. One definition, used by the posting
-- function and readable by reports.
-- ---------------------------------------------------------------------

create or replace function public.inventory_movement_direction(p_type text)
returns smallint
language sql
immutable
as $$
  select case p_type
    when 'opening_balance'     then 1
    when 'goods_receipt'       then 1
    when 'customer_return'     then 1
    when 'adjustment_increase' then 1
    when 'transfer_in'         then 1
    when 'count_increase'      then 1
    when 'requisition_return'  then 1
    when 'sale'                then -1
    when 'supplier_return'     then -1
    when 'adjustment_decrease' then -1
    when 'transfer_out'        then -1
    when 'count_decrease'      then -1
    when 'requisition_issue'   then -1
  end::smallint;
$$;

-- ---------------------------------------------------------------------
-- Posted movements are immutable. Corrections are new movements.
-- ---------------------------------------------------------------------

create or replace function public.fn_block_movement_mutation()
returns trigger
language plpgsql
as $$
begin
  raise exception
    'Stock movements cannot be % once posted. Reverse with an adjustment or a return instead.',
    case tg_op when 'UPDATE' then 'edited' else 'deleted' end;
end;
$$;

drop trigger if exists trg_movements_immutable on public.inventory_movements;
create trigger trg_movements_immutable
  before update or delete on public.inventory_movements
  for each row execute function public.fn_block_movement_mutation();

-- ---------------------------------------------------------------------
-- THE posting function.
--
-- SECURITY DEFINER so it can maintain balances and write the ledger even
-- though those tables refuse direct client writes. It still enforces the
-- caller's permissions itself — being definer removes RLS, not authority.
-- ---------------------------------------------------------------------

create or replace function public.post_inventory_movement(
  p_product_id             uuid,
  p_warehouse_id           uuid,
  p_movement_type          text,
  p_quantity               numeric,
  p_unit_cost              numeric default null,
  p_source_module          text default null,
  p_source_document_type   text default null,
  p_source_document_id     uuid default null,
  p_source_document_number text default null,
  p_movement_date          date default current_date,
  p_reason                 text default null,
  p_notes                  text default null
)
returns uuid
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_direction       smallint;
  v_balance         public.inventory_balances%rowtype;
  v_product         public.products%rowtype;
  v_warehouse       public.warehouses%rowtype;
  v_unit_cost       numeric(18, 6);
  v_new_qty         numeric(18, 4);
  v_new_avg         numeric(18, 6);
  v_new_value       numeric(18, 4);
  v_movement_id     uuid;
begin
  ------------------------------------------------------------------
  -- Validate inputs
  ------------------------------------------------------------------
  if p_quantity is null or p_quantity <= 0 then
    raise exception 'Movement quantity must be greater than zero (got %)', p_quantity;
  end if;

  v_direction := public.inventory_movement_direction(p_movement_type);
  if v_direction is null then
    raise exception 'Unknown stock movement type "%"', p_movement_type;
  end if;

  select * into v_product from public.products where id = p_product_id;
  if not found then
    raise exception 'Product % does not exist', p_product_id;
  end if;
  if not v_product.track_stock then
    raise exception 'Product "%" is not stock tracked', v_product.name;
  end if;

  select * into v_warehouse from public.warehouses where id = p_warehouse_id;
  if not found then
    raise exception 'Warehouse % does not exist', p_warehouse_id;
  end if;
  if v_warehouse.status <> 'active' then
    raise exception 'Warehouse "%" is not active', v_warehouse.name;
  end if;

  ------------------------------------------------------------------
  -- Lock the balance row for the rest of the transaction so two
  -- concurrent receipts cannot both read the same average and race.
  ------------------------------------------------------------------
  select * into v_balance
  from public.inventory_balances
  where product_id = p_product_id and warehouse_id = p_warehouse_id
  for update;

  if not found then
    insert into public.inventory_balances (product_id, warehouse_id, quantity, average_cost, total_value)
    values (p_product_id, p_warehouse_id, 0, 0, 0)
    on conflict (product_id, warehouse_id) do nothing;

    select * into v_balance
    from public.inventory_balances
    where product_id = p_product_id and warehouse_id = p_warehouse_id
    for update;
  end if;

  ------------------------------------------------------------------
  -- Cost the movement
  ------------------------------------------------------------------
  if v_direction = 1 then
    -- Inbound must state what it cost. Fall back to the catalogue's
    -- standard cost only when the caller genuinely has no figure.
    v_unit_cost := coalesce(p_unit_cost, nullif(v_balance.average_cost, 0), v_product.standard_cost);
    if v_unit_cost is null or v_unit_cost < 0 then
      raise exception 'A receipt needs a unit cost (product "%")', v_product.name;
    end if;

    v_new_qty := v_balance.quantity + p_quantity;

    if v_new_qty = 0 then
      v_new_avg := 0;
    elsif v_balance.quantity <= 0 then
      -- Coming back from zero or negative: the incoming cost IS the average.
      -- Blending against a negative quantity would produce nonsense.
      v_new_avg := v_unit_cost;
    else
      v_new_avg := ((v_balance.quantity * v_balance.average_cost) + (p_quantity * v_unit_cost)) / v_new_qty;
    end if;
  else
    -- Outbound leaves at the current weighted average. The caller does not
    -- get to choose the cost of a sale — that is what makes gross profit real.
    v_unit_cost := case
      when v_balance.average_cost > 0 then v_balance.average_cost
      else coalesce(p_unit_cost, v_product.standard_cost, 0)
    end;

    v_new_qty := v_balance.quantity - p_quantity;

    if v_new_qty < 0 then
      -- Two gates, both required: the warehouse must permit it AND the
      -- acting user must hold the override permission.
      if not v_warehouse.allow_negative_stock then
        raise exception
          'Not enough stock: % has % of "%" in %, and % was requested',
          v_warehouse.name, v_balance.quantity, v_product.name, v_warehouse.code, p_quantity;
      end if;
      if auth.uid() is not null and not public.has_permission('inventory.negative_stock.allow') then
        raise exception
          'Taking "%" below zero needs the "Allow negative stock" permission', v_product.name;
      end if;
    end if;

    v_new_avg := case when v_new_qty <= 0 then v_balance.average_cost else v_balance.average_cost end;
  end if;

  v_new_value := round(v_new_qty * v_new_avg, 4);

  ------------------------------------------------------------------
  -- Write the ledger row, then the balance. Same transaction: both
  -- succeed or neither does.
  ------------------------------------------------------------------
  insert into public.inventory_movements (
    product_id, warehouse_id, movement_type, quantity, direction,
    unit_cost, total_cost,
    balance_quantity, balance_average_cost, balance_value,
    source_module, source_document_type, source_document_id, source_document_number,
    movement_date, reason, notes, created_by
  ) values (
    p_product_id, p_warehouse_id, p_movement_type, p_quantity, v_direction,
    v_unit_cost, round(p_quantity * v_unit_cost, 4),
    v_new_qty, v_new_avg, v_new_value,
    p_source_module, p_source_document_type, p_source_document_id, p_source_document_number,
    coalesce(p_movement_date, current_date), p_reason, p_notes, auth.uid()
  )
  returning id into v_movement_id;

  update public.inventory_balances
     set quantity         = v_new_qty,
         average_cost     = v_new_avg,
         total_value      = v_new_value,
         last_movement_at = now(),
         updated_at       = now()
   where product_id = p_product_id and warehouse_id = p_warehouse_id;

  return v_movement_id;
end;
$$;

grant execute on function public.post_inventory_movement(
  uuid, uuid, text, numeric, numeric, text, text, uuid, text, date, text, text
) to authenticated;

grant execute on function public.inventory_movement_direction(text) to authenticated;

-- ---------------------------------------------------------------------
-- Valuation as at a date, rebuilt from the ledger.
--
-- Reports must never trust the live balance for a historical date —
-- this replays the movements and returns the closing position.
-- ---------------------------------------------------------------------

create or replace function public.inventory_valuation_as_at(
  p_as_at        date default current_date,
  p_warehouse_id uuid default null
)
returns table (
  product_id   uuid,
  warehouse_id uuid,
  quantity     numeric,
  average_cost numeric,
  total_value  numeric
)
language sql
stable
security invoker
set search_path = public, pg_temp
as $$
  select distinct on (m.product_id, m.warehouse_id)
    m.product_id,
    m.warehouse_id,
    m.balance_quantity,
    m.balance_average_cost,
    m.balance_value
  from public.inventory_movements m
  where m.movement_date <= p_as_at
    and (p_warehouse_id is null or m.warehouse_id = p_warehouse_id)
  order by m.product_id, m.warehouse_id, m.movement_date desc, m.movement_no desc;
$$;

grant execute on function public.inventory_valuation_as_at(date, uuid) to authenticated;

-- Balances are maintained only by the posting function.
create or replace function public.fn_block_balance_mutation()
returns trigger
language plpgsql
as $$
begin
  raise exception
    'Stock balances are maintained by post_inventory_movement(); they cannot be edited directly.';
end;
$$;
