// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://meeqfqagneykgpfbgkgd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1lZXFmcWFnbmV5a2dwZmJna2dkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODU4NTEzNzMsImV4cCI6MjEwMTQyNzM3M30.fXCUELfEwjtgwkEZg3GUsTx-aAdUc7aR1i_rdFP5Hmk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== "undefined" ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  },
});
